#!/bin/bash
#
# Creates docker base image from kickstart file
#
# Copyright (C) 2015  Tero Saarni
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

WORKDIR="$1"
CALLERID="$2"
KICKSTART="$3"
NAME="$4"

cd "$WORKDIR"

/usr/local/ami-creator/ami_creator/ami_creator.py -c "$KICKSTART" -n "$NAME"

echo "Exporting docker image: ${NAME}.tar.xz..."
virt-tar-out -a "${NAME}.img" / - | xz --best > "${NAME}.tar.xz"

chown $CALLERID "${NAME}.tar.xz"
