#!/bin/bash
#
# Creates Docker base image from kickstart file
#
# Copyright (C) 2015  Tero Saarni
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

DOCKER_CREATOR_APPLIANCE="tsaarni/docker-image-creator"

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 kickstart-file image-name" >&2
    exit 1
fi

KICKSTART="$1"
KICKSTART_BASENAME=$(basename "$KICKSTART")
NAME="$2"

if [ ! -r "$KICKSTART" ]; then
    echo "Error: Cannot read kickstart file: $KICKSTART" >&2
    exit 1
fi

if [ -r "${NAME}.tar.gz" ]; then
    echo "Error: Target image file already exists: ${NAME}.tar.gz" >&2
    exit 1
fi

if [[ "$NAME" == *\/* ]]; then
    echo "Error: Image name cannot contain '/': $NAME" >&2
    exit 1
fi

WORKDIR=$(mktemp -d /tmp/docker-image-creator-XXXXXXXXXXXXXX)

# Pass caller uid:gid to container so that it can chown image file from root
# back to caller's ownership
CALLERID="$(id --user):$(id --group)"

cp "$KICKSTART" $WORKDIR
docker run --rm -v $WORKDIR:$WORKDIR --privileged $DOCKER_CREATOR_APPLIANCE \
  "$WORKDIR" "$CALLERID" "$KICKSTART_BASENAME" "$NAME" 

if [ -r "${WORKDIR}/${NAME}.tar.gz" ]; then
    mv "${WORKDIR}/${NAME}.tar.gz" .
else
    echo "Error: Image creation failed." >&2
    exit 1
fi

rm -rf "$WORKDIR"

echo ""
echo "Image created successfully."
echo ""
echo "Run following command to import the image into docker:"
echo ""
echo "    docker import - [repository[:tag]] < ${NAME}.tar.gz"
echo ""
